version: '2'
services:
    elasticsearch1:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
        container_name: elasticsearch1
        restart: always
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - xpack.security.enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        mem_limit: 1g
        volumes:
            - esdata1:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        expose:
            - 9200
        networks:
            - esnet

    elasticsearch2:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
        restart: always
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - "discovery.zen.ping.unicast.hosts=elasticsearch1"
            - xpack.security.enabled=false
        ulimits:
            memlock:
                soft: -1
                hard: -1
        mem_limit: 1g
        volumes:
            - esdata2:/usr/share/elasticsearch/data
        networks:
            - esnet

    kibana:
        image: docker.elastic.co/kibana/kibana:5.4.3
        restart: always
        volumes:
            - ./kibana.yml:/usr/share/kibana/config/kibana.yml
        environment:
            - ELASTICSEARCH_URL="http://elasticsearch1:9200"
            - SERVER_HOST="kibana"
            - SERVER_PORT=5601
            - XPACK_SECURITY_ENABLED=false
        expose:
            - 5601
        networks:
            - esnet

    nginx:
        image: nginx:1.13
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./htpasswd.users:/etc/nginx/htpasswd.users
        expose:
            - 8000
        ports:
            - 8000:8000
            - 8001:8001
        networks:
            - esnet

volumes:
    esdata1:
        driver: local
    esdata2:
        driver: local

networks:
    esnet:
